theme: jekyll-theme-slate
title: "An Experimental Comparison of Neural Models for Controlling Evolved Modular Soft Robots"

url: 'https://giorgia-nadizar.github.io/' # your main domain
baseurl: 'NeuralModelsVSR/'
